CREATE WAREHOUSE IF NOT EXISTS RETAILPULSE_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS RETAILPULSE;

USE DATABASE RETAILPULSE;
USE WAREHOUSE RETAILPULSE_WH;

CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS STAGING;
CREATE SCHEMA IF NOT EXISTS INTERMEDIATE;
CREATE SCHEMA IF NOT EXISTS ANALYTICS;
CREATE SCHEMA IF NOT EXISTS AUDIT;

CREATE FILE FORMAT IF NOT EXISTS RAW.PARQUET_FORMAT
    TYPE = PARQUET
    USE_VECTORIZED_SCANNER = TRUE;

CREATE STAGE IF NOT EXISTS RAW.INGEST_STAGE
    FILE_FORMAT = (
        FORMAT_NAME = 'RETAILPULSE.RAW.PARQUET_FORMAT'
    );

CREATE TABLE IF NOT EXISTS RAW.CUSTOMERS_RAW (
    CUSTOMER_ID STRING,
    FIRST_NAME STRING,
    LAST_NAME STRING,
    EMAIL STRING,
    PHONE STRING,
    CITY STRING,
    COUNTRY STRING,
    CUSTOMER_SEGMENT STRING,
    CREATED_AT TIMESTAMP_LTZ,
    UPDATED_AT TIMESTAMP_LTZ,

    LOAD_FILENAME STRING,
    LOAD_FILE_ROW_NUMBER NUMBER,
    LOAD_TS TIMESTAMP_LTZ
);

CREATE TABLE IF NOT EXISTS RAW.PRODUCTS_RAW (
    PRODUCT_ID STRING,
    PRODUCT_NAME STRING,
    CATEGORY STRING,
    SUBCATEGORY STRING,
    BRAND STRING,
    UNIT_PRICE NUMBER(12, 2),
    UNIT_COST NUMBER(12, 2),
    ACTIVE BOOLEAN,
    CREATED_AT TIMESTAMP_LTZ,
    UPDATED_AT TIMESTAMP_LTZ,

    LOAD_FILENAME STRING,
    LOAD_FILE_ROW_NUMBER NUMBER,
    LOAD_TS TIMESTAMP_LTZ
);

CREATE TABLE IF NOT EXISTS RAW.STORES_RAW (
    STORE_ID STRING,
    STORE_NAME STRING,
    CITY STRING,
    REGION STRING,
    OPENING_DATE DATE,
    ACTIVE BOOLEAN,
    CREATED_AT TIMESTAMP_LTZ,
    UPDATED_AT TIMESTAMP_LTZ,

    LOAD_FILENAME STRING,
    LOAD_FILE_ROW_NUMBER NUMBER,
    LOAD_TS TIMESTAMP_LTZ
);

CREATE TABLE IF NOT EXISTS RAW.ORDERS_RAW (
    ORDER_ID STRING,
    CUSTOMER_ID STRING,
    STORE_ID STRING,
    CHANNEL STRING,
    ORDER_STATUS STRING,
    ORDER_DATE TIMESTAMP_LTZ,
    CURRENCY STRING,
    PAYMENT_METHOD STRING,
    CREATED_AT TIMESTAMP_LTZ,
    UPDATED_AT TIMESTAMP_LTZ,

    LOAD_FILENAME STRING,
    LOAD_FILE_ROW_NUMBER NUMBER,
    LOAD_TS TIMESTAMP_LTZ
);

CREATE TABLE IF NOT EXISTS RAW.ORDER_ITEMS_RAW (
    ORDER_ITEM_ID STRING,
    ORDER_ID STRING,
    PRODUCT_ID STRING,
    QUANTITY NUMBER,
    UNIT_PRICE NUMBER(12, 2),
    UNIT_COST NUMBER(12, 2),
    DISCOUNT_PERCENTAGE NUMBER(8, 4),
    CREATED_AT TIMESTAMP_LTZ,
    UPDATED_AT TIMESTAMP_LTZ,

    LOAD_FILENAME STRING,
    LOAD_FILE_ROW_NUMBER NUMBER,
    LOAD_TS TIMESTAMP_LTZ
);

CREATE TABLE IF NOT EXISTS RAW.RETURNS_RAW (
    RETURN_ID STRING,
    ORDER_ID STRING,
    ORDER_ITEM_ID STRING,
    PRODUCT_ID STRING,
    RETURNED_QUANTITY NUMBER,
    RETURN_REASON STRING,
    RETURN_STATUS STRING,
    RETURN_DATE DATE,
    REFUND_AMOUNT FLOAT,

    LOAD_FILENAME STRING,
    LOAD_FILE_ROW_NUMBER NUMBER,
    LOAD_TS TIMESTAMP_LTZ
);

CREATE TABLE IF NOT EXISTS RAW.INVENTORY_RAW (
    SNAPSHOT_DATE DATE,
    STORE_ID STRING,
    PRODUCT_ID STRING,
    AVAILABLE_QUANTITY NUMBER,
    RESERVED_QUANTITY NUMBER,
    DAMAGED_QUANTITY NUMBER,
    REORDER_THRESHOLD NUMBER,

    LOAD_FILENAME STRING,
    LOAD_FILE_ROW_NUMBER NUMBER,
    LOAD_TS TIMESTAMP_LTZ
);

CREATE TABLE IF NOT EXISTS RAW.DELIVERIES_RAW (
    DELIVERY_ID STRING,
    ORDER_ID STRING,
    CARRIER STRING,
    DELIVERY_STATUS STRING,
    EVENT_TIMESTAMP STRING,
    SHIPPING_DATE STRING,
    EXPECTED_DELIVERY_DATE STRING,
    ACTUAL_DELIVERY_DATE STRING,
    DESTINATION_CITY STRING,

    LOAD_FILENAME STRING,
    LOAD_FILE_ROW_NUMBER NUMBER,
    LOAD_TS TIMESTAMP_LTZ
);

CREATE TABLE IF NOT EXISTS AUDIT.LOAD_RUNS (
    RUN_ID STRING NOT NULL,
    STARTED_AT TIMESTAMP_LTZ NOT NULL,
    FINISHED_AT TIMESTAMP_LTZ,
    STATUS STRING NOT NULL,
    OBJECTS_FOUND NUMBER DEFAULT 0,
    OBJECTS_LOADED NUMBER DEFAULT 0,
    ROWS_LOADED NUMBER DEFAULT 0,
    ERROR_MESSAGE STRING
);

CREATE TABLE IF NOT EXISTS AUDIT.FILE_LOADS (
    LOAD_ID STRING NOT NULL,
    RUN_ID STRING NOT NULL,
    MINIO_OBJECT_KEY STRING NOT NULL,
    STAGE_FILE STRING,
    TARGET_TABLE STRING NOT NULL,
    ROWS_PARSED NUMBER DEFAULT 0,
    ROWS_LOADED NUMBER DEFAULT 0,
    STATUS STRING NOT NULL,
    COPY_QUERY_ID STRING,
    ERROR_MESSAGE STRING,
    LOADED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);
